// Reminder model + pure operations — MA-2 (KITTO_AMBIENT B2).
//
// PURE: the data shape plus the validation and the small set of list transforms
// the scheduler needs (due / next / add / remove / snooze). No clock, no IO, no
// randomness — the impure `ReminderManager` adapter injects `now`, generates ids,
// and persists. This mirrors the stretch/pomodoro split: a tested pure core under a
// thin runtime shell. A persisted reminder stores an *absolute* `fireAt` so it
// survives restart and fires across sleep/wake by a plain wall-clock comparison.

/** The longest message we keep — a speech bubble, not an essay. */
export const MAX_MESSAGE_LEN = 200;

export interface Reminder {
  /** Stable unique id (generated by the adapter; opaque here). */
  readonly id: string;
  /** What to say when it fires (trimmed, length-capped). */
  readonly message: string;
  /** When to fire, as epoch ms (absolute — the key to sleep/restart resilience). */
  readonly fireAt: number;
  /** When it was created, epoch ms — for stable ordering of equal fire times. */
  readonly createdAt: number;
}

/** Earliest-first ordering; ties broken by creation order so the queue is stable. */
function byFireAt(a: Reminder, b: Reminder): number {
  return a.fireAt - b.fireAt || a.createdAt - b.createdAt;
}

/** Sanitize one untrusted record (parsed JSON / form input); null if unusable. */
function validate(raw: unknown): Reminder | null {
  if (typeof raw !== "object" || raw === null) return null;
  const r = raw as Record<string, unknown>;
  const id = typeof r.id === "string" ? r.id : null;
  const message = typeof r.message === "string" ? r.message.trim().slice(0, MAX_MESSAGE_LEN) : null;
  const fireAt = typeof r.fireAt === "number" && Number.isFinite(r.fireAt) ? r.fireAt : null;
  if (id === null || !message || fireAt === null) return null;
  const createdAt =
    typeof r.createdAt === "number" && Number.isFinite(r.createdAt) ? r.createdAt : fireAt;
  return { id, message, fireAt, createdAt };
}

/**
 * Coerce an untrusted value (the parsed `reminders.json`, or an event payload) into
 * a clean, sorted reminder list — dropping anything malformed. Loading can never
 * throw, so a hand-edited or stale store degrades to "fewer reminders", never a crash.
 */
export function normalizeReminders(raw: unknown): Reminder[] {
  const arr = Array.isArray(raw) ? raw : [];
  const out: Reminder[] = [];
  for (const item of arr) {
    const r = validate(item);
    if (r) out.push(r);
  }
  return out.sort(byFireAt);
}

/** Every reminder due to fire at-or-before `now`, earliest first. */
export function dueReminders(list: readonly Reminder[], now: number): Reminder[] {
  return list.filter((r) => r.fireAt <= now).sort(byFireAt);
}

/** The single earliest reminder due at-or-before `now`, or null if none are due. */
export function nextDue(list: readonly Reminder[], now: number): Reminder | null {
  return dueReminders(list, now)[0] ?? null;
}

/** Insert a reminder, keeping the list sorted. */
export function addReminder(list: readonly Reminder[], r: Reminder): Reminder[] {
  return [...list, r].sort(byFireAt);
}

/** Remove the reminder with `id` (a no-op if absent). */
export function removeReminder(list: readonly Reminder[], id: string): Reminder[] {
  return list.filter((r) => r.id !== id);
}

/** Reschedule `id` to fire `ms` from `now` (snooze). Unknown id ⇒ list unchanged. */
export function snoozeReminder(
  list: readonly Reminder[],
  id: string,
  now: number,
  ms: number,
): Reminder[] {
  return list.map((r) => (r.id === id ? { ...r, fireAt: now + Math.max(0, ms) } : r)).sort(byFireAt);
}
